name: Test and publish

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn build
      - name: Run composer install
        run: docker run --rm --user $(id -u):$(id -g) -v $(pwd):/app docker.io/composer install --no-dev
      - name: Deploy to vendor dir
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
            REMOTE_HOST: "tools-dev.wmflabs.org"
            REMOTE_USER: ${{ secrets.TOOLFORGE_USER }}
            SSH_PRIVATE_KEY: ${{ secrets.TOOLFORGE_KEY }}
            ARGS: "-rltgoDzvO --delete"
            SOURCE: "vendor/"
            TARGET: "/data/project/dibabel/vendor"
      - name: Deploy to public_html dir
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
            REMOTE_HOST: "tools-dev.wmflabs.org"
            REMOTE_USER: ${{ secrets.TOOLFORGE_USER }}
            SSH_PRIVATE_KEY: ${{ secrets.TOOLFORGE_KEY }}
            ARGS: "-rltgoDzvO --delete"
            SOURCE: "build/"
            TARGET: "/data/project/dibabel/public_html"
